protected/modules/user/models/User.php
<?php

/**
 * This is the model class for table "{{user_user}}".
 *
 * The followings are the available columns in table '{{user_user}}':
 * @property integer $id
 * @property string $creation_date
 * @property string $change_date
 * @property string $first_name
 * @property string $middle_name
 * @property string $last_name
 * @property string $nick_name
 * @property string $email
 * @property integer $gender
 * @property string $avatar
 * @property string $password
 * @property string $salt
 * @property integer $status
 * @property integer $access_level
 * @property string $last_visit
 * @property string $registration_date
 * @property string $registration_ip
 * @property string $activation_ip
 */
class User extends YModel
{
    const GENDER_THING  = 0;
    const GENDER_MALE   = 1;
    const GENDER_FEMALE = 2;

    const STATUS_BLOCK      = 0;
    const STATUS_ACTIVE     = 1;
    const STATUS_NOT_ACTIVE = 2;

    const EMAIL_CONFIRM_NO  = 0;
    const EMAIL_CONFIRM_YES = 1;

    const ACCESS_LEVEL_USER  = 0;
    const ACCESS_LEVEL_ADMIN = 1;

    private $_oldAccess_level;

    /**
     * @return string the associated database table name
     */
    public function tableName()
    {
        return '{{user_user}}';
    }

    /**
     * Returns the static model of the specified AR class.
     * @return User the static model class
     */
    public static function model($className = __CLASS__)
    {
        return parent::model($className);
    }

    /**
     * @return array validation rules for model attributes.
     */
    public function rules()
    {
        $module = Yii::app()->getModule('user');

        return array(
            array('birth_date, site, about, location, online_status, nick_name, first_name, last_name, middle_name, email', 'filter', 'filter' => 'trim'),
            array('birth_date, site, about, location, online_status, nick_name, first_name, last_name, middle_name, email', 'filter', 'filter' => array($obj = new CHtmlPurifier(), 'purify')),
            array('nick_name, email, password', 'required'),
            array('first_name, last_name, middle_name, nick_name, email', 'length', 'max' => 50),
            array('password, salt, activate_key', 'length', 'max' => 32),
            array('site', 'length', 'max' => 100),
            array('about', 'length', 'max' => 300),
            array('location, online_status', 'length', 'max' => 150),
            array('registration_ip, activation_ip, registration_date', 'length', 'max' => 20),
            array('gender, status, access_level, use_gravatar, email_confirm', 'numerical', 'integerOnly' => true),
            array('email_confirm', 'in', 'range' => array_keys($this->emailConfirmStatusList)),
            array('use_gravatar', 'in', 'range' => array(0, 1)),
            array('gender', 'in', 'range' => array_keys($this->gendersList)),
            array('status', 'in', 'range' => array_keys($this->statusList)),
            array('access_level', 'in', 'range' => array_keys($this->getAccessLevelsList())),
            array('nick_name', 'match', 'pattern' => '/^[A-Za-z0-9_-]{2,50}$/', 'message' => Yii::t('UserModule.user', 'Неверный формат поля "{attribute}" допустимы только буквы и цифры, от 2 до 20 символов')),
            array('site', 'url', 'allowEmpty' => true),
            array('email', 'email'),
            array('email', 'unique', 'message' => Yii::t('UserModule.user', 'Данный email уже используется другим пользователем')),
            array('nick_name', 'unique', 'message' => Yii::t('UserModule.user', 'Данный ник уже используется другим пользователем')),
            array('avatar', 'file', 'types' => implode(',', $module->avatarExtensions), 'maxSize' => $module->avatarMaxSize, 'allowEmpty' => true),
            array('id, creation_date, change_date, middle_name, first_name, last_name, nick_name, email, gender, avatar, password, salt, status, access_level, last_visit, registration_date, registration_ip, activation_ip', 'safe', 'on' => 'search'),
        );
    }

    /**
     * @return array customized attribute labels (name=>label)
     */
    public function attributeLabels()
    {
        return array(
            'id'                => Yii::t('UserModule.user', 'Id'),
            'creation_date'     => Yii::t('UserModule.user', 'Дата активации'),
            'change_date'       => Yii::t('UserModule.user', 'Дата изменения'),
            'first_name'        => Yii::t('UserModule.user', 'Имя'),
            'last_name'         => Yii::t('UserModule.user', 'Фамилия'),
            'middle_name'       => Yii::t('UserModule.user', 'Отчество'),
            'nick_name'         => Yii::t('UserModule.user', 'Ник'),
            'email'             => Yii::t('UserModule.user', 'Email'),
            'gender'            => Yii::t('UserModule.user', 'Пол'),
            'password'          => Yii::t('UserModule.user', 'Пароль'),
            'salt'              => Yii::t('UserModule.user', 'Соль'),
            'status'            => Yii::t('UserModule.user', 'Статус'),
            'access_level'      => Yii::t('UserModule.user', 'Доступ'),
            'last_visit'        => Yii::t('UserModule.user', 'Последний визит'),
            'registration_date' => Yii::t('UserModule.user', 'Дата регистрации'),
            'registration_ip'   => Yii::t('UserModule.user', 'Ip регистрации'),
            'activation_ip'     => Yii::t('UserModule.user', 'Ip активации'),
            'activate_key'      => Yii::t('UserModule.user', 'Код активации'),
            'avatar'            => Yii::t('UserModule.user', 'Аватар'),
            'use_gravatar'      => Yii::t('UserModule.user', 'Граватар'),
            'email_confirm'     => Yii::t('UserModule.user', 'Email подтвержден'),
            'birth_date'        => Yii::t('UserModule.user', 'День рождения'),
            'site'              => Yii::t('UserModule.user', 'Сайт/блог'),
            'location'          => Yii::t('UserModule.user', 'Расположение'),
            'about'             => Yii::t('UserModule.user', 'О себе'),
        );
    }

    public function search()
    {
        $criteria = new CDbCriteria;

        $criteria->compare('id', $this->id);
        $criteria->compare('creation_date', $this->creation_date, true);
        $criteria->compare('change_date', $this->change_date, true);
        $criteria->compare('first_name', $this->first_name, true);
        $criteria->compare('middle_name', $this->first_name, true);
        $criteria->compare('last_name', $this->last_name, true);
        $criteria->compare('nick_name', $this->nick_name, true);
        $criteria->compare('email', $this->email, true);
        $criteria->compare('gender', $this->gender);
        $criteria->compare('password', $this->password, true);
        $criteria->compare('salt', $this->salt, true);
        $criteria->compare('status', $this->status);
        $criteria->compare('access_level', $this->access_level);
        $criteria->compare('last_visit', $this->last_visit, true);
        $criteria->compare('registration_date', $this->registration_date, true);
        $criteria->compare('registration_ip', $this->registration_ip, true);
        $criteria->compare('activation_ip', $this->activation_ip, true);

        return new CActiveDataProvider(get_class($this), array('criteria' => $criteria));
    }

    public function afterFind()
    {
        $this->_oldAccess_level = $this->access_level;
    }

    public function beforeSave()
    {
        $this->change_date = new CDbExpression(
            Yii::app()->db->schema instanceof CSqliteSchema
            ? 'DATETIME("now")'
            :'NOW()'
        );

        if (!$this->isNewRecord
            && $this->admin()->count() == 1
            && $this->_oldAccess_level == self::ACCESS_LEVEL_ADMIN
            && ($this->access_level == self::ACCESS_LEVEL_USER || $this->status != self::STATUS_ACTIVE)
        ) {
            return false;
        }

        if ($this->isNewRecord) {
            $this->registration_date = $this->creation_date = $this->change_date;
            $this->registration_ip   = $this->activation_ip = Yii::app()->request->userHostAddress;
            $this->activate_key      = $this->generateActivationKey();
        }

        if ($this->birth_date === '')
            unset($this->birth_date);

        return parent::beforeSave();
    }

    public function beforeDelete()
    {
        if (User::model()->admin()->count() == 1 && $this->_oldAccess_level == self::ACCESS_LEVEL_ADMIN)
            return false;

        return parent::beforeDelete();
    }

    public function scopes()
    {
        return array(
            'active'       => array(
                'condition' => 'status = :status',
                'params'    => array(':status' => self::STATUS_ACTIVE),
            ),
            'blocked'      => array(
                'condition' => 'status = :status',
                'params'    => array(':status' => self::STATUS_BLOCK),
            ),
            'notActivated' => array(
                'condition' => 'status = :status',
                'params'    => array(':status' => self::STATUS_NOT_ACTIVE),
            ),
            'admin'        => array(
                'condition' => 'access_level = :access_level',
                'params'    => array(':access_level' => self::ACCESS_LEVEL_ADMIN),
            ),
            'user'         => array(
                'condition' => 'access_level = :access_level',
                'params'    => array(':access_level' => self::ACCESS_LEVEL_USER),
            ),
        );
    }

    public function validatePassword($password)
    {
        if ($this->password === $this->hashPassword($password, $this->salt))
            return true;
        return false;
    }

    public function getAccessLevelsList()
    {
        return array(
            self::ACCESS_LEVEL_ADMIN => Yii::t('UserModule.user', 'Администратор'),
            self::ACCESS_LEVEL_USER  => Yii::t('UserModule.user', 'Пользователь'),
        );
    }

protected/modules/user/controllers/DefaultController.php
<?php
class DefaultController extends YBackController
{
    /**
     * @var CActiveRecord the currently loaded data model instance.
     */
    private $_model;

    /**
     * Displays a particular model.
     */
    public function actionView()
    {
        $this->render('view', array('model' => $this->loadModel()));
    }

    public function actionChangepassword()
    {
        $model = $this->loadModel();

        $form = new ChangePasswordForm;

        if (Yii::app()->request->isPostRequest && !empty($_POST['ChangePasswordForm']))
        {
            $form->setAttributes($_POST['ChangePasswordForm']);

            if ($form->validate() && $model->changePassword($form->password))
            {
                $model->changePassword($form->password);

                Yii::app()->user->setFlash(
                    YFlashMessages::NOTICE_MESSAGE,
                    Yii::t('UserModule.user', 'Пароль успешно изменен!')
                );
                $this->redirect(array('/user/default/view', 'id' => $model->id));
            }
        }
        $this->render('changepassword', array('model' => $model, 'changePasswordForm' => $form));
    }

    /**
     * Creates a new model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     */
    public function actionCreate()
    {
        $model = new User;

        if (Yii::app()->request->isPostRequest && !empty($_POST['User']))
        {
            $model->setAttributes($_POST['User']);

            $model->setAttributes(array(
                'salt'              => $model->generateSalt(),
                'password'          => $model->hashPassword($model->password, $model->salt),
                'registration_ip'   => Yii::app()->request->userHostAddress,
                'activation_ip'     => Yii::app()->request->userHostAddress,
                'registration_date' => new CDbExpression("NOW()"),
            ));

            if ($model->save())
            {
                Yii::app()->user->setFlash(
                    YFlashMessages::NOTICE_MESSAGE,
                    Yii::t('UserModule.user', 'Новый пользователь добавлен!')
                );

                $this->redirect(
                    (array) Yii::app()->request->getPost(
                        'submit-type', array('create')
                    )
                );
            }
        }
        $this->render('create', array('model' => $model));
    }

    /**
     * Updates a particular model.
     * If update is successful, the browser will be redirected to the 'view' page.
     */
    public function actionUpdate()
    {
        $model = $this->loadModel();

        if (Yii::app()->request->isPostRequest && !empty($_POST['User']))
        {
            $model->setAttributes($_POST['User']);

            if ($model->save())
            {
                Yii::app()->user->setFlash(
                    YFlashMessages::NOTICE_MESSAGE,
                    Yii::t('UserModule.user', 'Данные обновлены!')
                );

                if (!isset($_POST['submit-type']))
                    $this->redirect(array('update', 'id' => $model->id));
                else
                    $this->redirect(array($_POST['submit-type']));
            }
        }
        $this->render('update', array('model' => $model));
    }

    /**
     * Deletes a particular model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     */
    public function actionDelete()
    {
        if (Yii::app()->request->isPostRequest)
        {
            // we only allow deletion via POST request
            $this->loadModel()->delete();

            // if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
            if (!isset($_GET['ajax']))
                $this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('index'));
        }
        else
            throw new CHttpException(400, Yii::t('UserModule.user', 'Неверный запрос. Пожалуйста, больше не повторяйте такие запросы!'));
    }

    /**
     * Manages all models.
     */
    public function actionIndex()
    {
        $model = new User('search');
        $model->unsetAttributes(); // clear any default values
        if (isset($_GET['User']))
            $model->attributes = $_GET['User'];
        $this->render('index', array('model' => $model));
    }

    /**
     * Для отправки письма с активацией:
     *
     * @return void
     */
    public function actionSendactivation($id)
    {
        if (($user = User::model()->findbyPk($id)) === null) {
            if (!Yii::app()->request->isPostRequest || !Yii::app()->request->isAjaxRequest) {
                Yii::app()->user->setFlash(
                    YFlashMessages::ERROR_MESSAGE,
                    Yii::t('UserModule.user', 'Пользователь #{id} не найден!', array('{id}' => $id))
                );
                $this->redirect(array('index'));
            } else
                Yii::app()->ajax->failure(
                    Yii::t('UserModule.user', 'Пользователь #{id} не найден!', array('{id}' => $id))
                );
        }

        // отправка email с просьбой активировать аккаунт
        $mailBody = $this->renderPartial('needAccountActivationEmail', array('model' => $user), true);
        
        Yii::app()->mail->send(
            $this->module->notifyEmailFrom,
            $user->email,
            Yii::t('UserModule.user', 'Регистрация на сайте {site} !', array('{site}' => Yii::app()->name)),
            $mailBody
        );

        if (!Yii::app()->request->isPostRequest || !Yii::app()->request->isAjaxRequest) {
            Yii::app()->user->setFlash(
                YFlashMessages::NOTICE_MESSAGE,
                Yii::t('UserModule.user', 'Письмо с активацией отправлено пользователю #{id}!', array('{id}' => $id))
            );
            $this->redirect(array('index'));
        } else
            Yii::app()->ajax->success(
                Yii::t('UserModule.user', 'Письмо с активацией отправлено пользователю #{id}!', array('{id}' => $id))
            );
    }

    /**
     * Returns the data model based on the primary key given in the GET variable.
     * If the data model is not found, an HTTP exception will be raised.
     * @return User
     */
    public function loadModel()
    {
        if ($this->_model === null)
        {
            if (isset($_GET['id']))
                $this->_model = User::model()->findbyPk($_GET['id']);
            if ($this->_model === null)
                throw new CHttpException(404, Yii::t('UserModule.user', 'Запрошенная страница не найдена!'));
        }
        return $this->_model;
    }

    /**
     * Performs the AJAX validation.
     * @param CModel the model to be validated
     */
    protected function performAjaxValidation($model)
    {
        if (isset($_POST['ajax']) && $_POST['ajax'] === 'user-form')
        {
            echo CActiveForm::validate($model);
            Yii::app()->end();
        }
    }
}

protected/modules/user/views/default/_form.php
<?php
$form = $this->beginWidget('bootstrap.widgets.TbActiveForm', array(
    'id'                     => 'user-form',
    'enableAjaxValidation'   => false,
    'enableClientValidation' => true,
    'type'                   => 'vertical',
    'htmlOptions'            => array('class' => 'well'),
    'inlineErrors'           => true,
)); ?>
 
    <div class="alert alert-info">
        <?php echo Yii::t('UserModule.user', 'Поля, отмеченные'); ?>
        <span class="required">*</span>
        <?php echo Yii::t('UserModule.user', 'обязательны.'); ?>
    </div>

    <?php echo $form->errorSummary($model); ?>

    <div class="row-fluid control-group <?php echo $model->hasErrors('nick_name') ? 'error' : ''; ?>">
        <?php echo $form->textFieldRow($model, 'nick_name', array('class' => 'popover-help span7', 'maxlength' => 150, 'size' => 60, 'data-original-title' => $model->getAttributeLabel('nick_name'), 'data-content' => $model->getAttributeDescription('nick_name'))); ?>
    </div>
    <div class="row-fluid control-group <?php echo $model->hasErrors('email') ? 'error' : ''; ?>">
        <?php echo $form->textFieldRow($model, 'email', array('class' => 'popover-help span7', 'maxlength' => 150, 'size' => 60, 'data-original-title' => $model->getAttributeLabel('email'), 'data-content' => $model->getAttributeDescription('email'))); ?>
    </div>
    <div class="row-fluid control-group <?php echo $model->hasErrors('last_name') ? 'error' : ''; ?>">
        <?php echo $form->textFieldRow($model, 'last_name', array('class' => 'popover-help span7', 'maxlength' => 150, 'size' => 60, 'data-original-title' => $model->getAttributeLabel('last_name'), 'data-content' => $model->getAttributeDescription('last_name'))); ?>
    </div>
    <div class="row-fluid control-group <?php echo $model->hasErrors('first_name') ? 'error' : ''; ?>">
        <?php echo $form->textFieldRow($model, 'first_name', array('class' => 'popover-help span7', 'maxlength' => 150, 'size' => 60, 'data-original-title' => $model->getAttributeLabel('first_name'), 'data-content' => $model->getAttributeDescription('first_name'))); ?>
    </div>
    <div class="row-fluid control-group <?php echo $model->hasErrors('middle_name') ? 'error' : ''; ?>">
        <?php echo $form->textFieldRow($model, 'middle_name', array('class' => 'popover-help span7', 'maxlength' => 150, 'size' => 60, 'data-original-title' => $model->getAttributeLabel('middle_name'), 'data-content' => $model->getAttributeDescription('middle_name'))); ?>
    </div>
    <div class="row-fluid control-group <?php echo $model->hasErrors('site') ? 'error' : ''; ?>">
        <?php echo $form->textFieldRow($model, 'site', array('class' => 'popover-help span7', 'maxlength' => 150, 'size' => 60, 'data-original-title' => $model->getAttributeLabel('site'), 'data-content' => $model->getAttributeDescription('site'))); ?>
    </div>
    <div class="row-fluid control-group <?php echo $model->hasErrors('birth_date') ? 'error' : ''; ?>">
        <?php echo $form->labelEx($model, 'birth_date'); ?>
        <?php $this->widget('zii.widgets.jui.CJuiDatePicker', array(
            'model'     => $model,
            'attribute' => 'birth_date',
            'options'   => array('dateFormat' => 'yy-mm-dd'),
            'htmlOptions' => array('class' => 'span7')
        )); ?>
    </div>
    <div class="row-fluid control-group <?php echo $model->hasErrors('about') ? 'error' : ''; ?>">
        <div class="popover-help" data-original-title='<?php echo $model->getAttributeLabel('about'); ?>' data-content='<?php echo $model->getAttributeDescription('about'); ?>'>
            <?php echo $form->textAreaRow($model, 'about', array('class' => 'span7')); ?>
        </div>
    </div>
    <div class="row-fluid control-group <?php echo $model->hasErrors('gender') ? 'error' : ''; ?>"> 
        <?php echo $form->dropDownListRow($model, 'gender', $model->gendersList,array('class' => 'popover-help span7','data-original-title' => $model->getAttributeLabel('gender'), 'data-content' => $model->getAttributeDescription('gender'))); ?>
    </div>
    <div class="row-fluid control-group <?php echo $model->hasErrors('status') ? 'error' : ''; ?>"> 
        <?php echo $form->dropDownListRow($model, 'status', $model->statusList,array('class' => 'popover-help span7','data-original-title' => $model->getAttributeLabel('status'), 'data-content' => $model->getAttributeDescription('status'))); ?>
    </div>
    <div class="row-fluid control-group <?php echo $model->hasErrors('access_level') ? 'error' : ''; ?>">     
        <?php echo $form->dropDownListRow($model, 'access_level', $model->accessLevelsList,array('class' => 'popover-help span7','data-original-title' => $model->getAttributeLabel('access_level'), 'data-content' => $model->getAttributeDescription('access_level'))); ?>        
    </div>
    <div class="row-fluid control-group <?php echo $model->hasErrors('email_confirm') ? 'error' : ''; ?>"> 
        <?php echo $form->dropDownListRow($model, 'email_confirm', $model->emailConfirmStatusList,array('class' => 'popover-help span7','data-original-title' => $model->getAttributeLabel('email_confirm'), 'data-content' => $model->getAttributeDescription('email_confirm'))); ?>
    </div>

   <?php $this->widget('bootstrap.widgets.TbButton', array(
        'buttonType' => 'submit',
        'type'       => 'primary',
        'label'      => $model->isNewRecord ? Yii::t('UserModule.user', 'Добавить пользователя и продолжить') : Yii::t('UserModule.user', 'Сохранить пользователя и продолжить'),
    )); ?>
    <?php $this->widget('bootstrap.widgets.TbButton', array(
        'buttonType'  => 'submit',
        'htmlOptions' => array('name' => 'submit-type', 'value' => 'index'),
        'label'       => $model->isNewRecord ? Yii::t('UserModule.user', 'Добавить пользователя и закрыть') : Yii::t('UserModule.user', 'Сохранить пользователя и закрыть'),
    )); ?>

<?php $this->endWidget(); ?>

protected/modules/user/views/default/_search.php
<?php
$form = $this->beginWidget('bootstrap.widgets.TbActiveForm', array(
    'action'      => Yii::app()->createUrl($this->route),
    'method'      => 'get',
    'type'        => 'vertical',
    'htmlOptions' => array('class' => 'well'),
)); ?>
    <fieldset class="inline">
        <?php echo $form->textFieldRow($model, 'nick_name', array('size' => 60, 'maxlength' => 150)); ?>
        <?php echo $form->textFieldRow($model, 'email', array('size' => 60, 'maxlength' => 150)); ?>
        <?php echo $form->textFieldRow($model, 'first_name', array('size' => 60, 'maxlength' => 150)); ?>
        <?php echo $form->textFieldRow($model, 'last_name', array('size' => 60, 'maxlength' => 150)); ?> 
        <?php echo $form->textFieldRow($model, 'creation_date'); ?>
        <?php echo $form->textFieldRow($model, 'change_date'); ?>
        <?php echo $form->dropDownListRow($model, 'gender', $model->getGendersList()); ?>
        <?php echo $form->dropDownListRow($model, 'status', $model->getStatusList()); ?>
        <?php echo $form->dropDownListRow($model, 'access_level', $model->getAccessLevelsList()); ?>
        <?php echo $form->textFieldRow($model, 'last_visit'); ?>
        <?php echo $form->textFieldRow($model, 'registration_date'); ?>
        <?php echo $form->textFieldRow($model, 'registration_ip', array('size' => 20, 'maxlength' => 20)); ?>
        <?php echo $form->textFieldRow($model, 'activation_ip', array('size' => 20, 'maxlength' => 20)); ?>
    </fieldset>

    <?php $this->widget('bootstrap.widgets.TbButton', array(
        'buttonType'  => 'submit',
        'type'        => 'primary',
        'encodeLabel' => false,
        'label'       => '<i class="icon-search icon-white">&nbsp;</i> '.Yii::t('UserModule.user', 'Искать пользователя'),
    )); ?>

<?php $this->endWidget(); ?>

protected/modules/user/views/default/changepassword.php
<?php
    $this->breadcrumbs = array(
        Yii::app()->getModule('user')->getCategory() => array(),
        Yii::t('UserModule.user', 'Пользователи') => array('/user/default/index'),
        $model->nick_name => array('/user/default/view', 'id' => $model->id),
        Yii::t('UserModule.user', 'Изменение паролья'),
    );

    $this->pageTitle = Yii::t('UserModule.user', 'Пользователи - изменение пароля');

    $this->menu = array(
        array('label' => Yii::t('UserModule.user', 'Пользователи'), 'items' => array(
            array('icon' => 'list-alt', 'label' => Yii::t('UserModule.user', 'Управление пользователями'), 'url' => array('/user/default/index')),
            array('icon' => 'plus-sign', 'label' => Yii::t('UserModule.user', 'Добавление пользователя'), 'url' => array('/user/default/create')),
            array('label' => Yii::t('UserModule.user', 'Пользователь') . ' «' . $model->nick_name . '»'),
            array('icon' => 'pencil', 'label' => Yii::t('UserModule.user', 'Редактирование пользователя'), 'url' => array(
                '/user/default/update',
                'id' => $model->id
            )),
            array('icon' => 'eye-open', 'label' => Yii::t('UserModule.user', 'Просмотр пользователя'), 'url' => array(
                '/user/default/view',
                'id' => $model->id
            )),
            array('icon' => 'lock', 'label' => Yii::t('UserModule.user', 'Изменить пароль пользователя'), 'url' => array(
                '/user/default/changepassword',
                'id' => $model->id
            )),
            array('icon' => 'trash', 'label' => Yii::t('UserModule.user', 'Удалить пользователя'), 'url' => '#', 'linkOptions' => array(
                'submit' => array('/user/default/delete', 'id' => $model->id),
                'params' => array(Yii::app()->request->csrfTokenName => Yii::app()->request->csrfToken),
                'confirm' => Yii::t('UserModule.user', 'Вы уверены, что хотите удалить пользователя?')),
            ),
        )),
        array('label' => Yii::t('UserModule.user', 'Восстановления паролей'), 'items' => array(
            array('icon' => 'list-alt', 'label' => Yii::t('UserModule.user', 'Восстановления паролей'), 'url' => array('/user/recoveryPassword/index')),
        )),
    );
?>
<div class="page-header">
    <h1>
        <?php echo Yii::t('UserModule.user', 'Изменение пароля'); ?><br />
        <small>&laquo;<?php echo $model->nick_name; ?>&raquo;</small>
    </h1>
</div>

<?php
$form = $this->beginWidget('bootstrap.widgets.TbActiveForm', array(
    'id'                     => 'user-form',
    'enableAjaxValidation'   => false,
    'enableClientValidation' => true,
    'type'                   => 'vertical',
    'htmlOptions'            => array('class' => 'well'),
    'inlineErrors'           => true,
)); ?>
    <?php echo $form->errorSummary($changePasswordForm); ?>

    <div class="row-fluid control-group <?php echo $model->hasErrors('password') ? 'error' : ''; ?>"> 
        <?php echo $form->passwordFieldRow($changePasswordForm, 'password'); ?>
    </div>
    <div class="row-fluid control-group <?php echo $model->hasErrors('cPassword') ? 'error' : ''; ?>"> 
        <?php echo $form->passwordFieldRow($changePasswordForm, 'cPassword'); ?>
    </div>

    <?php $this->widget('bootstrap.widgets.TbButton', array(
        'buttonType' => 'submit',
        'type'       => 'primary',
        'label'      =>  Yii::t('UserModule.user', 'Изменить пароль'),
    )); ?>

<?php $this->endWidget(); ?>

protected/modules/user/views/default/needAccountActivationEmail.php
<html>
<head>
    <title><?php echo Yii::t('UserModule.user', 'Успешная активация аккаунта!'); ?></title>
</head>
<body>
    <?php echo Yii::t('UserModule.user', 'Вы успешно зарегистрировались на сайте "{site}" !', array('{site}' => CHtml::encode(Yii::app()->name))); ?>

    <br/><br/>

    <?php echo Yii::t('UserModule.user', 'Для активации аккаунта, пожалуйста, перейдите по'); ?>
    &nbsp;<?php echo CHtml::link(Yii::t('UserModule.user', 'ссылке'), $link = Yii::app()->createAbsoluteUrl('/user/account/activate', array('key' => $model->activate_key))); ?>
    <br/><br/>

    <?php  echo $link; ?>

    <br/><br/>

    <?php echo Yii::t('UserModule.user', 'С уважением, администрация сайта "{site}" !', array('{site}' => CHtml::encode(Yii::app()->name))); ?>
</body>
</html>