protected/modules/menu/models/MenuItem.php
<?php

/**
 * This is the model class for table "menu_item".
 *
 * The followings are the available columns in table 'menu_item':
 * @property string $id
 * @property string $parent_id
 * @property string $menu_id
 * @property string $title
 * @property string $href
 * @property string $class
 * @property string $title_attr
 * @property string $before_link
 * @property string $after_link
 * @property string $target
 * @property string $rel
 * @property string $condition_name
 * @property integer $condition_denial
 * @property integer $sort
 * @property integer $status
 * @property boolean $regular_link
 *
 * The followings are the available model relations:
 * @property Menu $menu
 */
class MenuItem extends YModel
{
    const STATUS_DISABLED = 0;
    const STATUS_ACTIVE   = 1;

    /**
     * Returns the static model of the specified AR class.
     * @param string $className active record class name.
     * @return MenuItem the static model class
     */
    public static function model($className = __CLASS__)
    {
        return parent::model($className);
    }

    /**
     * @return string the associated database table name
     */
    public function tableName()
    {
        return '{{menu_menu_item}}';
    }

    /**
     * @return array validation rules for model attributes.
     */
    public function rules()
    {
        // NOTE: you should only define rules for those attributes that
        // will receive user inputs.
        return array(
            array('parent_id, menu_id, title, href', 'required', 'except' => 'search'),
            array('sort, status, condition_denial', 'numerical', 'integerOnly' => true),
            array('parent_id, menu_id, rel, target', 'length', 'max' => 10),
            array('title, href, condition_name, title_attr, before_link, after_link', 'length', 'max' => 255),
            array('class', 'length', 'max' => 50),
            array('regular_link', 'boolean'),
            // The following rule is used by search().
            // Please remove those attributes that should not be searched.
            array('id, parent_id, menu_id, title, href, sort, status, condition_name, condition_denial', 'safe', 'on' => 'search'),
        );
    }

    /**
     * @return array relational rules.
     */
    public function relations()
    {
        // NOTE: you may need to adjust the relation name and the related
        // class name for the relations automatically generated below.
        return array(
            'menu'   => array(self::BELONGS_TO, 'Menu', 'menu_id'),
            'parent' => array(self::BELONGS_TO, 'MenuItem', 'parent_id')
        );
    }

    /**
     * @return array customized attribute labels (name=>label)
     */
    public function attributeLabels()
    {
        return array(
            'id'               => Yii::t('MenuModule.menu', 'Id'),
            'parent_id'        => Yii::t('MenuModule.menu', 'Родитель'),
            'menu_id'          => Yii::t('MenuModule.menu', 'Меню'),
            'title'            => Yii::t('MenuModule.menu', 'Заголовок'),
            'href'             => Yii::t('MenuModule.menu', 'Адрес'),
            'title_attr'       => Yii::t('MenuModule.menu', 'Атрибут title'),
            'class'            => Yii::t('MenuModule.menu', 'Атрибут class'),
            'rel'              => Yii::t('MenuModule.menu', 'Атрибут rel'),
            'target'           => Yii::t('MenuModule.menu', 'Атрибут target'),
            'before_link'      => Yii::t('MenuModule.menu', 'Текст перед ссылкой'),
            'after_link'       => Yii::t('MenuModule.menu', 'Текст после ссылки'),
            'condition_name'   => Yii::t('MenuModule.menu', 'Условие'),
            'condition_denial' => Yii::t('MenuModule.menu', 'Отрицание условия'),
            'sort'             => Yii::t('MenuModule.menu', 'Сортировка'),
            'status'           => Yii::t('MenuModule.menu', 'Статус'),
            'regular_link'     => Yii::t('MenuModule.menu', 'Обычная ссылка'),
        );
    }

    /**
     * @return array customized attribute descriptions (name=>description)
     */
    public function attributeDescriptions()
    {
        return array(
            'id'               => Yii::t('MenuModule.menu', 'Id пункта меню.'),
            'parent_id'        => Yii::t('MenuModule.menu', 'Родитель данного пункта меню. Если пункт необходимо указать в корне, выберите корень меню.'),
            'menu_id'          => Yii::t('MenuModule.menu', 'Укажите к какому меню относится данный пункт.'),
            'title'            => Yii::t('MenuModule.menu', 'Заголовок пункта меню.'),
            'href'             => Yii::t('MenuModule.menu', 'Адрес странице на сайте.'),
            'class'            => Yii::t('MenuModule.menu', 'Добавляет необходимые классы тегу &lt;li&gt;'),
            'title_attr'       => Yii::t('MenuModule.menu', 'Добавляет подсказку к ссылке'),
            'rel'              => Yii::t('MenuModule.menu', 'Используется для указания xfr'),
            'target'           => Yii::t('MenuModule.menu', 'Используется для указания открытия новой страницы в новом окне или вкладке, фрейме.'),
            'before_link'      => Yii::t('MenuModule.menu', 'Текст перед ссылкой'),
            'after_link'       => Yii::t('MenuModule.menu', 'Текст после ссылки'),
            'condition_name'   => Yii::t('MenuModule.menu', 'Если данный пункт меню, необходимо выводить только при определенном условии, укажите его.'),
            'condition_denial' => Yii::t('MenuModule.menu', 'Условие применяется при совпадении или отрацании.'),
            'sort'             => Yii::t('MenuModule.menu', 'Порядковый номер пункта в меню.'),
            'status'           => Yii::t('MenuModule.menu', 'Установите статус пункта меню: <br /><br /><span class="label label-success">активно</span> &ndash; пункт меню и все его потомки выводятся.<br /><br /><span class="label label-warning">не активно</span> &ndash; пункт меню и все его потомки выводиться не будут.'),
            'regular_link'     => Yii::t('MenuModule.menu', 'Не обрабатывать адрес роутером'),
        );
    }

    /**
     * Retrieves a list of models based on the current search/filter conditions.
     * @return CActiveDataProvider the data provider that can return the models based on the search/filter conditions.
     */
    public function search()
    {
        // Warning: Please modify the following code to remove attributes that
        // should not be searched.

        $criteria = new CDbCriteria;

        $criteria->compare('id', $this->id, true);
        $criteria->compare('parent_id', $this->parent_id, true);
        $criteria->compare('t.menu_id', $this->menu_id, true);
        $criteria->compare('title', $this->title, true);
        $criteria->compare('href', $this->href, true);

        if ($this->condition_name != '0') {
            $criteria->compare('t.condition_name', $this->condition_name, true);
            if ($this->condition_name != '')
                $criteria->compare('t.condition_denial', $this->condition_denial);
        } else
            $criteria->condition('t.condition_name', '');

        $criteria->compare('sort', $this->sort);
        $criteria->compare('status', $this->status);
        $criteria->with = array('menu','parent');

        return new CActiveDataProvider(
            get_class($this), array(
                'criteria' => $criteria,
                'sort'     => array('defaultOrder' => 't.sort')
            )
        );
    }

    protected function afterSave()
    {
        Yii::app()->cache->clear($this->menu->code);
    }

    protected function afterDelete()
    {
        Yii::app()->cache->clear($this->menu->code);
    }

    public function getMenuList()
    {
        return CHtml::listData(Menu::model()->findAll(array('select' => 'id, name')), 'id', 'name');
    }

    public function getStatusList()
    {
        return array(
            self::STATUS_ACTIVE   => Yii::t('MenuModule.menu', 'активно'),
            self::STATUS_DISABLED => Yii::t('MenuModule.menu', 'не активно'),
        );
    }

    public function getStatus()
    {
        $data = $this->statusList;
        return isset($data[$this->status]) ? $data[$this->status] : Yii::t('MenuModule.menu', '*неизвестно*');
    }

    public function getParentList()
    {
        return array(0 => Yii::t('MenuModule.menu', 'Корень меню')) + CHtml::listData($this->findAll(array('select' => 'id, title')), 'id', 'title');
    }

    public function getParentTree()
    {
        return array(0 => Yii::t('MenuModule.menu', 'Корень меню')) + $this->parentTreeIterator;
    }

    public function getParentTreeIterator($parent_id = 0, $level = 1)
    {
        $results = $this->findAll(array(
            'order'     => 'sort',
            'condition' => 'parent_id = :parent_id AND id <> :id AND menu_id = :menu_id',
            'params'    => array(
                'parent_id' => (int) $parent_id,
                'id'        => (int) $this->id,
                'menu_id'   => (int) $this->menu_id,
            ),
        ));

        $items = array();
        if (empty($results))
            return $items;

        foreach ($results as $result)
        {
            $childItems = $this->getParentTreeIterator($result->id, ($level + 1));
            $items += array($result->id => str_repeat('&nbsp;&nbsp;&nbsp;&nbsp;', $level) . $result->title) + $childItems;
        }
        return $items;
    }

    public function getParent()
    {
        return empty($this->parent) ? '---' : $this->parent->title;
    }

    public function getConditionList($condition = false)
    {
        $conditions = array();

        foreach (Yii::app()->modules as $key => $value)
        {
            $key = strtolower($key);
            $module = Yii::app()->getModule($key);

            if (($module !== NULL) && is_a($module, 'YWebModule') && isset($module->conditions))
            {
                $conditionsList = array();

protected/modules/menu/controllers/MenuitemController.php
<?php

class MenuitemController extends YBackController
{
    /**
     * Отображает пункт меню по указанному идентификатору
     * @param integer $id Идинтификатор меню для отображения
     */
    public $pages;
    public $result = array();

    public function actionView($id)
    {
        $this->render('view', array('model' => $this->loadModel($id)));
    }

    /**
     * Создает новую модель пунта меню.
     * Если создание прошло успешно - перенаправляет на просмотр.
     */
    public function actionCreate()
    {
        $model = new MenuItem;

        // Uncomment the following line if AJAX validation is needed
        // $this->performAjaxValidation($model);

        if ($mid = (int) Yii::app()->request->getQuery('mid'))
            $model->menu_id = $mid;

        if (isset($_POST['MenuItem']))
        {
            $model->attributes = $_POST['MenuItem'];

            if ($model->save())
            {
                $this->redirect(
                    (array) Yii::app()->request->getPost(
                        'submit-type', array('create')
                    )
                );
            }
        }

        $criteria = new CDbCriteria;
        $criteria->select = new CDbExpression('MAX(sort) as sort');
        $max = $model->find($criteria);

        $model->sort = $max->sort + 1; // Set sort in Adding Form as ma x+ 1

        $this->render('create', array('model' => $model));
    }

    /**
     * Редактирование пункта меню.
     * @param integer $id Идинтификатор пункта меню для редактирования
     */
    public function actionUpdate($id)
    {
        $model = $this->loadModel($id);

        // Uncomment the following line if AJAX validation is needed
        // $this->performAjaxValidation($model);

        if (isset($_POST['MenuItem']))
        {
            $model->attributes = $_POST['MenuItem'];

            if ($model->save())
            {
                 if (!isset($_POST['submit-type']))
                    $this->redirect(array('update', 'id' => $model->id));
                 else
                    $this->redirect(array($_POST['submit-type']));
            }
        }
        $this->render('update', array('model' => $model));
    }

    /**
     * Удаляет модель пункта меню из базы.
     * Если удаление прошло успешно - возвращется в index
     * @param integer $id идентификатор пункта меню, который нужно удалить
     */
    public function actionDelete($id)
    {
        if (Yii::app()->request->isPostRequest)
        {
            // we only allow deletion via POST request
            $this->loadModel($id)->delete();

            // if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
            if (!isset($_GET['ajax']))
                $this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('index'));
        }
        else
            throw new CHttpException(400, Yii::t('MenuModule.menu', 'Неверный запрос. Пожалуйста, больше не повторяйте такие запросы!'));
    }

    /**
     * Управление пунктами меню.
     */
    public function actionIndex()
    {
        $model = new MenuItem('search');
        $model->unsetAttributes();  // clear any default values
        if (isset($_GET['MenuItem']))
            $model->attributes = $_GET['MenuItem'];
        $this->render('index', array('model' => $model));
    }

    /**
     * Обновление дерева пунктов меню в завимости от родителя.
     */
    public function actionDynamicParent()
    {
        if (Yii::app()->request->isAjaxRequest && isset($_POST['MenuItem']))
        {
            $model = new MenuItem('search');
            $model->attributes = $_POST['MenuItem'];
            if ($model->menu_id)
            {
                if (isset($_GET['id']))
                    $model->id = $_GET['id'];
                $data = $model->parentTree;
                foreach ($data as $value => $name)
                    echo CHtml::tag('option', array('value' => $value), $name, true);
            }
        }
        Yii::app()->end();
    }

    /**
     * Возвращает модель по указанному идентификатору
     * Если модель не будет найдена - возникнет HTTP-исключение.
     * @param integer идентификатор нужной модели
     */
    public function loadModel($id)
    {
        $model = MenuItem::model()->findByPk($id);
        if ($model === null)
            throw new CHttpException(404, Yii::t('MenuModule.menu', 'Запрошенная страница не найдена!'));
        return $model;
    }

    /**
     * Производит AJAX-валидацию
     * @param CModel модель, которую необходимо валидировать
     */
    protected function performAjaxValidation($model)
    {
        if (isset($_POST['ajax']) && $_POST['ajax'] === 'menuitem-form')
        {
            echo CActiveForm::validate($model);
            Yii::app()->end();
        }
    }

    public function actionGetPageTree() {
        $page = new Page();
        $result = $page->tree();

        echo CJavaScript::jsonEncode($result);
        Yii::getLogger()->flush();
        Yii::app()->end();
    }

}

protected/modules/menu/views/menuitem/_form.php
<?php
$form = $this->beginWidget('bootstrap.widgets.TbActiveForm', array(
    'id'                     => 'menu-item-form',
    'enableAjaxValidation'   => false,
    'enableClientValidation' => true,
    'type'                   => 'vertical',
    'htmlOptions'            => array('class' => 'well'),
    'inlineErrors'           => true,
)); ?>
    <div class="alert alert-info">
        <?php echo Yii::t('MenuModule.menu', 'Поля, отмеченные'); ?>
        <span class="required">*</span>
        <?php echo Yii::t('MenuModule.menu', 'обязательны.'); ?>
    </div>

    <?php echo $form->errorSummary($model); ?>

<div class="wide row-fluid control-group <?php echo ($model->hasErrors('menu_id') || $model->hasErrors('parent_id')) ? 'error' : ''; ?>">
    <?php
    $menu_id   = '#' . CHtml::activeId($model, 'menu_id');
    $parent_id = '#' . CHtml::activeId($model, 'parent_id');
    ?>
    <div class="span3">
        <?php echo $form->dropDownListRow($model, 'menu_id', CHtml::listData(Menu::model()->findAll(), 'id', 'name'), array(
            'empty'               => Yii::t('MenuModule.menu', '--выберите меню--'),
            'class'               => 'popover-help',
            'data-original-title' => $model->getAttributeLabel('menu_id'),
            'data-content'        => $model->getAttributeDescription('menu_id'),
            'ajax' => array(
                'type'       => 'POST',
                'url'        => $this->createUrl('/menu/menuitem/dynamicparent', (!$model->isNewRecord ? array('id' => $model->id) : array())),
                'update'     => $parent_id,
                'beforeSend' => "function() {
                            $('" . $parent_id . "').attr('disabled', true);
                            if ($('" . $menu_id . " option:selected').val() == '')
                                return false;
                        }",
                'complete'   => "function() {
                            $('" . $parent_id . "').attr('disabled', false);
                        }",
            ),
        )); ?>
    </div>
    <div class="span4">
        <?php echo $form->dropDownListRow($model, 'parent_id', $model->parentTree, array('disabled' => ($model->menu_id) ? false : true) + array('encode' => false, 'class' => 'popover-help', 'data-original-title' => $model->getAttributeLabel('parent_id'), 'data-content' => $model->getAttributeDescription('parent_id'))); ?>
    </div>
</div>

    <div class="row-fluid control-group <?php echo $model->hasErrors("title") ? "error" : ""; ?>">
        <?php echo $form->textFieldRow($model, 'title', array('class' => 'popover-help span7', 'maxlength' => 255, 'data-original-title' => $model->getAttributeLabel('title'), 'data-content' => $model->getAttributeDescription('title'))); ?>
    </div>

    <div class="row-fluid control-group <?php echo $model->hasErrors("href") ? "error" : ""; ?>">
        <?php echo $form->textFieldRow($model, 'href', array('class' => 'popover-help span7', 'maxlength' => 220, 'data-original-title' => $model->getAttributeLabel('href'), 'data-content' => $model->getAttributeDescription('href'))); ?>
        <a href="#category_tree_popup" rel="category_tree"><img style="margin-top: -10px;" src="/web/images/32.png"></a>
    </div>

    <div class="row-fluid control-group <?php echo $model->hasErrors("sort") ? "error" : ""; ?>">
        <?php echo $form->textFieldRow($model, 'sort', array('class' => 'popover-help span7', 'maxlength' => 255, 'data-original-title' => $model->getAttributeLabel('sort'), 'data-content' => $model->getAttributeDescription('sort'))); ?>
    </div>

    <div class="row-fluid control-group <?php echo $model->hasErrors('status') ? 'error' : ''; ?>">
        <?php echo $form->dropDownListRow($model, 'status', $model->statusList, array('class' => 'span7 popover-help', 'data-original-title' => $model->getAttributeLabel('status'), 'data-content' => $model->getAttributeDescription('status'))); ?>
    </div>

     <div class="row-fluid control-group <?php echo $model->hasErrors("regular_link") ? "error" : ""; ?>">
         <?php echo $form->checkBoxRow($model, 'regular_link', array('class' => 'popover-help', 'data-original-title' => $model->getAttributeLabel('regular_link'), 'data-content' => $model->getAttributeDescription('regular_link'))); ?>
    </div>

    <?php $collapse = $this->beginWidget('bootstrap.widgets.TbCollapse');?>
    <div class="accordion-group">
        <div class="accordion-heading">
            <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapseOne">
                <?php echo Yii::t('MenuModule.menu','Расширенные параметры');?>
            </a>
        </div>
        <div id="collapseOne" class="accordion-body collapse">
            <div class="accordion-inner">
                <div class="row-fluid control-group <?php echo $model->hasErrors("title_attr") ? "error" : ""; ?>">
                    <?php echo $form->textFieldRow($model, 'title_attr', array('class' => 'popover-help span7', 'maxlength' => 255, 'data-original-title' => $model->getAttributeLabel('title_attr'), 'data-content' => $model->getAttributeDescription('title_attr'))); ?>
                </div>
                <div class="row-fluid control-group <?php echo $model->hasErrors("class") ? "error" : ""; ?>">
                    <?php echo $form->textFieldRow($model, 'class', array('class' => 'popover-help span7', 'maxlength' => 50, 'data-original-title' => $model->getAttributeLabel('class'), 'data-content' => $model->getAttributeDescription('class'))); ?>
                </div>
                <div class="wide row-fluid control-group <?php echo ($model->hasErrors('before_link') || $model->hasErrors('after_link')) ? 'error' : ''; ?>">
                    <div class="span3">
                        <?php echo $form->textFieldRow($model, 'before_link', array('class' => 'popover-help span7', 'maxlength' => 255, 'data-original-title' => $model->getAttributeLabel('before_link'), 'data-content' => $model->getAttributeDescription('before_link'))); ?>
                    </div>
                    <div class="span4">
                        <?php echo $form->textFieldRow($model, 'after_link', array('class' => 'popover-help span7', 'maxlength' => 255, 'data-original-title' => $model->getAttributeLabel('after_link'), 'data-content' => $model->getAttributeDescription('after_link'))); ?>
                    </div>
                </div>
                <div class="wide row-fluid control-group <?php echo ($model->hasErrors('target') || $model->hasErrors('rel')) ? 'error' : ''; ?>">
                    <div class="span3">
                        <?php echo $form->textFieldRow($model, 'target', array('class' => 'popover-help span7', 'maxlength' => 10, 'data-original-title' => $model->getAttributeLabel('target'), 'data-content' => $model->getAttributeDescription('target'))); ?>
                    </div>
                    <div class="span4">
                        <?php echo $form->textFieldRow($model, 'rel', array('class' => 'popover-help span7', 'maxlength' => 10, 'data-original-title' => $model->getAttributeLabel('rel'), 'data-content' => $model->getAttributeDescription('rel'))); ?>
                    </div>
                </div>
                <div class="wide row-fluid control-group <?php echo ($model->hasErrors('condition_name') || $model->hasErrors('condition_denial')) ? 'error' : ''; ?>">
                    <div class="span4">
                        <?php echo $form->dropDownListRow($model, 'condition_name', $model->conditionList, array('empty' => '', 'class' => 'popover-help', 'data-original-title' => $model->getAttributeLabel('condition_name'), 'data-content' => $model->getAttributeDescription('condition_name'))); ?>
                    </div>
                    <div class="span3">
                        <?php echo $form->dropDownListRow($model, 'condition_denial', $model->conditionDenialList, array('class' => 'popover-help', 'data-original-title' => $model->getAttributeLabel('condition_denial'), 'data-content' => $model->getAttributeDescription('condition_denial'))); ?>
                    </div>
                </div>

            </div>
        </div>
    </div>
    <?php $this->endWidget();?>

    <br/>

    <?php $this->widget('bootstrap.widgets.TbButton', array(
        'buttonType' => 'submit',
        'type'       => 'primary',
        'label'      => $model->isNewRecord ? Yii::t('MenuModule.menu', 'Добавить пункт меню и продолжить') : Yii::t('MenuModule.menu', 'Сохранить пункт меню и продолжить'),
    )); ?>
    <?php $this->widget('bootstrap.widgets.TbButton', array(
        'buttonType'  => 'submit',
        'htmlOptions' => array('name' => 'submit-type', 'value' => 'index'),
        'label'       => $model->isNewRecord ? Yii::t('MenuModule.menu', 'Добавить пункт меню и закрыть') : Yii::t('MenuModule.menu', 'Сохранить пункт меню и закрыть'),
    )); ?>

<?php


$this->widget('application.extensions.fancybox.EFancyBox', array(
    'target'=>'a[rel=category_tree]',
    'config'=>array(
        'autoDimensions' => false,
    ),
));
?>
<?php $this->endWidget(); ?>
<div style="display:none">
    <div id="category_tree_popup">
        <?php
        $this->widget('application.extensions.jstree.JsTree', array(
                'id' => 'category_tree',
                'config' => array(
                    'core' => array(
                        'initially_open' => array("node_root"),
                        'load_open' => false
                    ),
                    'plugins' => array(
                        'themes', 'json_data',  'ui', 'hotkeys'
                    ),
                    'ui' => array(
                        'select_limit' => 0
                    ),
                    "themes" => array(
                        "icons" => false
                    ),
//                    "checkbox" => array(
//                        "override_ui" => true,
//                        //"two_state" => true
//                    ),
                    "json_data" => array(
                        "ajax" => array(
                            "url" => $this->createAbsoluteUrl('/menu/menuitem/getpagetree'),
                            //"success" => 'js:function (data) { console.log($(\'.menu-item\')) }'
                        )
                    )
                ),
                'operations' => array(
                    'check_node' => 'js:function(e, data) {
						//data.inst.open_all(data.rslt.obj, false);
					}',
                    'loaded.jstree' => 'js:function(e, data) {
                        $(\'.menu-item\').click(function() {
                            $(\'#MenuItem_href\').val($(this).data(\'url\'));
                            jQuery.fancybox.close();
                        });
					}',

                ),

            )
        );
        ?>
    </div>
</div>
<?php

?>

protected/modules/menu/views/menuitem/_search.php
<?php
$form = $this->beginWidget('bootstrap.widgets.TbActiveForm', array(
    'action'      => Yii::app()->createUrl($this->route),
    'method'      => 'get',
    'type'        => 'vertical',
    'htmlOptions' => array('class' => 'well'),
)); ?>

    <fieldset>
        <?php echo $form->textFieldRow($model, 'id') ?>
        <?php echo $form->textFieldRow($model, 'title'); ?>
        <?php echo $form->textFieldRow($model, 'href'); ?>
        <?php echo $form->dropDownListRow($model, 'menu_id', CHtml::listData(Menu::model()->findAll(), 'id', 'name'), array('empty' => Yii::t('MenuModule.menu', 'выберите меню'))); ?>
        <?php echo $form->dropDownListRow($model, 'parent_id', $model->parentList); ?>
        <?php echo $form->dropDownListRow($model, 'condition_name', $model->conditionList); ?>
        <?php echo $form->dropDownListRow($model, 'condition_denial', $model->conditionDenialList); ?>
        <?php echo $form->textFieldRow($model, 'sort'); ?>
        <?php echo $form->dropDownListRow($model, 'status', $model->statusList); ?>
    </fieldset>

    <?php $this->widget('bootstrap.widgets.TbButton', array(
        'type'        => 'primary',
        'encodeLabel' => false,
        'buttonType'  => 'submit',
        'label'       => '<i class="icon-search icon-white">&nbsp;</i> ' . Yii::t('blog', 'Искать пункт меню'),
    )); ?>

<?php $this->endWidget(); ?>

protected/modules/menu/views/menuitem/create.php
<?php
    $this->breadcrumbs = array(
        Yii::app()->getModule('menu')->getCategory() => array(),
        Yii::t('MenuModule.menu', 'Меню') => array('/menu/menu/index'),
        Yii::t('MenuModule.menu', 'Пункты меню') => array('/menu/menuitem/index'),
        Yii::t('MenuModule.menu', 'Добавление'),
    );

    $this->pageTitle = Yii::t('MenuModule.menu', 'Пункты меню - добавление');

    $this->menu = array(
        array('label' => Yii::t('MenuModule.menu', 'Меню'), 'items' => array(
            array('icon' => 'plus-sign', 'label' => Yii::t('MenuModule.menu', 'Добавить меню'), 'url' => array('/menu/menu/create')),
            array('icon' => 'list-alt', 'label' => Yii::t('MenuModule.menu', 'Управление меню'), 'url' => array('/menu/menu/index')),
        )),
        array('label' => Yii::t('MenuModule.menu', 'Пункты меню'), 'items' => array(
            array('icon' => 'plus-sign', 'label' => Yii::t('MenuModule.menu', 'Добавить пункт меню'), 'url' => array('/menu/menuitem/create')),
            array('icon' => 'list-alt', 'label' => Yii::t('MenuModule.menu', 'Управление пунктами меню'), 'url' => array('/menu/menuitem/index')),
        )),
    );
?>
<div class="page-header">
    <h1>
        <?php echo Yii::t('MenuModule.menu', 'Пункт меню'); ?>
        <small><?php echo Yii::t('MenuModule.menu', 'добавление'); ?></small>
    </h1>
</div>

<?php echo $this->renderPartial('_form', array('model' => $model)); ?>