protected/modules/news/models/News.php
<?php

/**
 * This is the model class for table "News".
 *
 * The followings are the available columns in table 'News':
 * @property integer $id
 * @property string $creation_date
 * @property string $change_date
 * @property string $date
 * @property string $title
 * @property string $alias
 * @property string $short_text
 * @property string $full_text
 * @property integer $user_id
 * @property integer $status
 * @property integer $is_protected
 * @property string  $link
 * @property string  $image
 */
class News extends YModel
{

    const STATUS_DRAFT      = 0;
    const STATUS_PUBLISHED  = 1;
    const STATUS_MODERATION = 2;

    const PROTECTED_NO  = 0;
    const PROTECTED_YES = 1;

    /**
     * @return string the associated database table name
     */
    public function tableName()
    {
        return '{{news_news}}';
    }

    /**
     * Returns the static model of the specified AR class.
     * @param string $className
     * @return News the static model class
     */
    public static function model($className = __CLASS__)
    {
        return parent::model($className);
    }

    /**
     * @return array validation rules for model attributes.
     */
    public function rules()
    {
        return array(
            array('title, alias, short_text, full_text, keywords, description', 'filter', 'filter' => 'trim'),
            array('title, alias, keywords, description', 'filter', 'filter' => 'strip_tags'),
            array('date, title, alias, full_text', 'required', 'on' => array('update', 'insert')),
            array('status, is_protected, category_id', 'numerical', 'integerOnly' => true),
            array('title, alias, keywords', 'length', 'max' => 150),
            array('lang', 'length', 'max' => 2),
            array('lang', 'default', 'value' => Yii::app()->sourceLanguage),
            array('lang', 'in', 'range' => array_keys(Yii::app()->getModule('yupe')->getLanguagesList())),
            array('status', 'in', 'range' => array_keys($this->statusList)),
            array('alias', 'YUniqueSlugValidator'),
            array('description', 'length', 'max' => 250),
            array('link', 'length', 'max' => 250),
            array('link', 'YUrlValidator'),
            array('alias', 'YSLugValidator', 'message' => Yii::t('NewsModule.news', 'Запрещенные символы в поле {attribute}')),
            array('category_id', 'default', 'setOnEmpty' => true, 'value' => null),
            array('id, keywords, description, creation_date, change_date, date, title, alias, short_text, full_text, user_id, status, is_protected, lang', 'safe', 'on' => 'search'),
        );
    }

    public function behaviors()
    {
        $module = Yii::app()->getModule('news');
        return array(
            'imageUpload' => array(
                'class'         =>'application.modules.yupe.models.ImageUploadBehavior',
                'scenarios'     => array('insert','update'),
                'attributeName' => 'image',
                'minSize'       => $module->minSize,
                'maxSize'       => $module->maxSize,
                'types'         => $module->allowedExtensions,              
                'uploadPath'    => $module->getUploadPath(),
                'imageNameCallback' => array($this, 'generateFileName'),
                'resize' => array(
                    'quality' => 75,
                    'width' => 800,
                )
            ),
        );
    }

    public function generateFileName()
    {
        return md5($this->title . microtime(true));
    }
    /**
     * @return array relational rules.
     */
    public function relations()
    {
        return array(
            'category' => array(self::BELONGS_TO, 'Category', 'category_id'),
            'user'     => array(self::BELONGS_TO, 'User', 'user_id'),
        );
    }

    public function scopes()
    {
        return array(
            'published' => array(
                'condition' => 't.status = :status',
                'params'    => array(':status'   => self::STATUS_PUBLISHED),
            ),
            'protected' => array(
                'condition' => 't.is_protected = :is_protected',
                'params'    => array(':is_prtected' => self::PROTECTED_YES),
            ),
            'public'    => array(
                'condition' => 't.is_protected = :is_protected',
                'params'    => array(':is_protected' => self::PROTECTED_NO),
            ),
            'recent'    => array(
                'order' => 'creation_date DESC',
                'limit' => 5,
            )
        );
    }

    public function last($num)
    {
        $this->getDbCriteria()->mergeWith(array(
            'order' => 'date DESC',
            'limit' => $num,
        ));
        return $this;
    }

    public function language($lang)
    {
        $this->getDbCriteria()->mergeWith(array(
            'condition' => 'lang = :lang',
            'params'    => array(':lang' => $lang),
        ));
        return $this;
    }

    public function category($category_id)
    {
        $this->getDbCriteria()->mergeWith(array(
            'condition' => 'category_id = :category_id',
            'params'    => array(':category_id' => $category_id),
        ));
        return $this;
    }

    /**
     * @return array customized attribute labels (name=>label)
     */
    public function attributeLabels()
    {
        return array(
            'id'            => Yii::t('NewsModule.news', 'Id'),
            'category_id'   => Yii::t('NewsModule.news', 'Категория'),
            'creation_date' => Yii::t('NewsModule.news', 'Дата создания'),
            'change_date'   => Yii::t('NewsModule.news', 'Дата изменения'),
            'date'          => Yii::t('NewsModule.news', 'Дата'),
            'title'         => Yii::t('NewsModule.news', 'Заголовок'),
            'alias'         => Yii::t('NewsModule.news', 'Алиас'),
            'image'         => Yii::t('NewsModule.news', 'Изображение'),
            'link'          => Yii::t('NewsModule.news', 'Ссылка'),
            'lang'          => Yii::t('NewsModule.news', 'Язык'),
            'short_text'    => Yii::t('NewsModule.news', 'Короткий текст'),
            'full_text'     => Yii::t('NewsModule.news', 'Полный текст'),
            'user_id'       => Yii::t('NewsModule.news', 'Автор'),
            'status'        => Yii::t('NewsModule.news', 'Статус'),
            'is_protected'  => Yii::t('NewsModule.news', 'Доступ: * только для авторизованных пользователей'),
            'keywords'      => Yii::t('NewsModule.news', 'Ключевые слова (SEO)'),
            'description'   => Yii::t('NewsModule.news', 'Описание (SEO)'),
        );
    }

    public function beforeValidate()
    {
        if (!$this->alias)
            $this->alias = YText::translit($this->title);

        if(!$this->lang)
            $this->lang = Yii::app()->language;

        return parent::beforeValidate();
    }

    public function beforeSave()
    {
        $this->change_date = YDbMigration::expression('NOW()');
        $this->date        = date('Y-m-d', strtotime($this->date));

        if ($this->isNewRecord)
        {
            $this->creation_date = $this->change_date;
            $this->user_id       = Yii::app()->user->getId();
        }

        return parent::beforeSave();
    }

    public function afterFind()
    {
        parent::afterFind();

        $this->date = date('d.m.Y', strtotime($this->date));
    }

    /**
     * Retrieves a list of models based on the current search/filter conditions.
     * @return CActiveDataProvider the data provider that can return the models based on the search/filter conditions.
     */
    public function search()
    {
        // Warning: Please modify the following code to remove attributes that
        // should not be searched.

        $criteria = new CDbCriteria;

        $criteria->compare('t.id', $this->id);
        $criteria->compare('creation_date', $this->creation_date, true);
        $criteria->compare('change_date', $this->change_date, true);
        $criteria->compare('date', $this->date, true);
        $criteria->compare('title', $this->title, true);
        $criteria->compare('t.alias', $this->alias, true);
        $criteria->compare('short_text', $this->short_text, true);
        $criteria->compare('full_text', $this->full_text, true);
        $criteria->compare('user_id', $this->user_id);
        if ($this->status != '')
            $criteria->compare('t.status', $this->status);
        if ($this->category_id != '')
            $criteria->compare('category_id', $this->category_id);
        $criteria->compare('is_protected', $this->is_protected);
        $criteria->compare('t.lang', $this->lang);
        $criteria->with = array('category');
        return new CActiveDataProvider(get_class($this), array(
            'criteria' => $criteria,
            'sort'     => array('defaultOrder' => 'date DESC'),
        ));
    }

    public function getPermaLink()
    {
        return Yii::app()->createAbsoluteUrl('/news/news/show/', array('title' => $this->alias));
    }

    public function getStatusList()
    {
        return array(
            self::STATUS_DRAFT      => Yii::t('NewsModule.news', 'Черновик'),
            self::STATUS_PUBLISHED  => Yii::t('NewsModule.news', 'Опубликовано'),
            self::STATUS_MODERATION => Yii::t('NewsModule.news', 'На модерации'),
        );
    }

    public function getStatus()
    {
        $data = $this->getStatusList();
        return isset($data[$this->status]) ? $data[$this->status] : Yii::t('NewsModule.news', '*неизвестно*');
    }

    public function getProtectedStatusList()
    {
        return array(
            self::PROTECTED_NO  => Yii::t('NewsModule.news', 'нет'),
            self::PROTECTED_YES => Yii::t('NewsModule.news', 'да'),
        );
    }

    public function getProtectedStatus()
    {
        $data = $this->getProtectedStatusList();

protected/modules/news/controllers/DefaultController.php
<?php

class DefaultController extends YBackController
{
    /**
     * Displays a particular model.
     * @param integer $id the ID of the model to be displayed
     */
    public function actionView($id)
    {
        $this->render('view', array('model' => $this->loadModel($id)));
    }

    /**
     * Creates a new model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     */
    public function actionCreate()
    {
        $model = new News;

        // Uncomment the following line if AJAX validation is needed
        // $this->performAjaxValidation($model);

        if (Yii::app()->request->isPostRequest && isset($_POST['News']))
        {
            $model->setAttributes(Yii::app()->request->getPost('News'));

            if ($model->save())
            {
                Yii::app()->user->setFlash(
                    YFlashMessages::NOTICE_MESSAGE,
                    Yii::t('NewsModule.news', 'Новость добавлена!')
                );

                $this->redirect(
                    (array) Yii::app()->request->getPost(
                        'submit-type', array('create')
                    )
                );
            }
        }

        $languages = $this->yupe->getLanguagesList();

        //если добавляем перевод
        $id = (int)Yii::app()->request->getQuery('id');
        $lang = Yii::app()->request->getQuery('lang');

        if(!empty($id) && !empty($lang)){
            $news = News::model()->findByPk($id);
            if(null === $news){
                Yii::app()->user->setFlash(YFlashMessages::ERROR_MESSAGE,Yii::t('NewsModule.news','Целевая новость не найдена!'));
                $this->redirect(array('/news/default/create'));
            }
            if(!array_key_exists($lang,$languages)){
                Yii::app()->user->setFlash(YFlashMessages::ERROR_MESSAGE,Yii::t('NewsModule.news','Язык не найден!'));
                $this->redirect(array('/news/default/create'));
            }
            Yii::app()->user->setFlash(YFlashMessages::NOTICE_MESSAGE,Yii::t('NewsModule.news','Вы добавляете перевод на {lang} язык!',array(
                        '{lang}' => $languages[$lang]
                    )));
            $model->lang = $lang;
            $model->alias = $news->alias;
            $model->date = $news->date;
            $model->category_id = $news->category_id;
            $model->title = $news->title;
        }else{
            $model->date = date('d.m.Y');
            $model->lang = Yii::app()->language;
        }

        $this->render('create', array('model' => $model, 'languages' => $languages));
    }

    /**
     * Updates a particular model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param null $alias
     * @param integer $id the ID of the model to be updated
     * @throws CHttpException
     * @return void
     */
    public function actionUpdate($id)
    {
        $model = $this->loadModel((int)$id);

        if (Yii::app()->request->isPostRequest && isset($_POST['News'])) {
            $model->setAttributes(Yii::app()->request->getPost('News'));
            if ($model->save()) {
                Yii::app()->user->setFlash(
                    YFlashMessages::NOTICE_MESSAGE,
                    Yii::t('NewsModule.news', 'Новость обновлена!')
                );

                if (!isset($_POST['submit-type']))
                    $this->redirect(array('update', 'id' => $model->id));
                else
                    $this->redirect(array($_POST['submit-type']));

                $this->redirect(array('view', 'id' => $model->id));
            }
        }

        // найти по alias страницы на других языках
        $langModels = News::model()->findAll('alias = :alias AND id != :id',array(
            ':alias' => $model->alias,
            ':id' => $model->id
        ));

        $this->render('update',array(
            'langModels' => CHtml::listData($langModels,'lang','id'),
            'model' => $model,
            'languages' => $this->yupe->getLanguagesList()
        ));
    }

    /**
     * Deletes a particular model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param null $alias
     * @param integer $id the ID of the model to be deleted
     * @throws CHttpException
     * @return void
     */
    public function actionDelete($id = null)
    {
        if (Yii::app()->request->isPostRequest)
        {
            $this->loadModel($id)->delete();
            // if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
            if (!isset($_GET['ajax']))
                $this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('index'));
        }
        else
            throw new CHttpException(400, Yii::t('NewsModule.news', 'Неверный запрос. Пожалуйста, больше не повторяйте такие запросы!'));
    }

    /**
     * Manages all models.
     */
    public function actionIndex()
    {
        $model = new News('search');
        $model->unsetAttributes(); // clear any default values
        if (isset($_GET['News']))
            $model->attributes = $_GET['News'];
        $this->render('index', array('model' => $model));
    }

    /**
     * Returns the data model based on the primary key given in the GET variable.
     * If the data model is not found, an HTTP exception will be raised.
     * @param integer the ID of the model to be loaded
     */
    public function loadModel($id)
    {
        $model = News::model()->findByPk((int)$id);
        if ($model === null)
            throw new CHttpException(404, Yii::t('catalog', 'Запрошенная страница не найдена!'));
        return $model;
    }

    /**
     * Performs the AJAX validation.
     * @param CModel the model to be validated
     */
    protected function performAjaxValidation($model)
    {
        if (isset($_POST['ajax']) && $_POST['ajax'] === 'news-form')
        {
            echo CActiveForm::validate($model);
            Yii::app()->end();
        }
    }
}

protected/modules/news/views/default/_form.php
<script type='text/javascript'>
    $(document).ready(function(){
        $('#news-form').liTranslit({
            elName: '#News_title',
            elAlias: '#News_alias'
        });
    })
</script>

<?php
$form = $this->beginWidget('bootstrap.widgets.TbActiveForm', array(
    'id'                     => 'news-form',
    'enableAjaxValidation'   => false,
    'enableClientValidation' => true,
    'type'                   => 'vertical',
    'htmlOptions'            => array('class' => 'well', 'enctype'=>'multipart/form-data'),
    'inlineErrors'           => true,
)); ?>
    <div class="alert alert-info">
        <?php echo Yii::t('NewsModule.news', 'Поля, отмеченные'); ?>
        <span class="required">*</span>
        <?php echo Yii::t('NewsModule.news', 'обязательны.'); ?>
    </div>

    <?php echo $form->errorSummary($model); ?>

    <?php if(count($languages) > 1):?>
        <?php echo $form->dropDownListRow($model, 'lang', $languages, array('class' => 'popover-help','empty' => Yii::t('NewsModule.news', '--выберите--'))); ?>
        <?php if(!$model->isNewRecord):?>
            <?php foreach($languages as $k => $v):?>
                <?php if($k !== $model->lang):?>
                    <?php if(empty($langModels[$k])):?>
                        <a href="<?php echo $this->createUrl('/news/default/create',array('id' => $model->id,'lang'  => $k));?>"><i class="iconflags iconflags-<?php echo $k;?>" title="<?php echo Yii::t('NewsModule.news','Добавить перевод на {lang} язык',array('{lang}' => $v))?>"></i></a>
                    <?php else:?>
                        <a href="<?php echo $this->createUrl('/news/default/update',array('id' => $langModels[$k]));?>"><i class="iconflags iconflags-<?php echo $k;?>" title="<?php echo Yii::t('NewsModule.news','Редактировать перевод на {lang} язык',array('{lang}' => $v))?>"></i></a>
                    <?php endif;?>
                <?php endif;?>
            <?php endforeach;?>
        <?php endif;?>
    <?php else:?>
        <?php echo $form->hiddenField($model,'lang');?>
    <?php endif;?>

    <div class="row-fluid control-group <?php echo $model->hasErrors('date') ? 'error' : ''; ?>">
        <div class="span4 popover-help" data-original-title='<?php echo $model->getAttributeLabel('date'); ?>' data-content='<?php echo $model->getAttributeDescription('date'); ?>'>
            <?php
            echo $form->datepickerRow(
                $model, 'date', array(
                    'prepend' => '<i class="icon-calendar"></i>',
                    'options' => array(
                        'format'    => 'dd.mm.yyyy',
                        'weekStart' => 1,
                        'autoclose' => true,
                    ),
                    'class'   => 'span11'
                )
            ); ?>
        </div>
    </div>

    <div class="row-fluid control-group <?php echo $model->hasErrors('category_id') ? 'error' : ''; ?>">
        <?php echo $form->dropDownListRow($model, 'category_id', CHtml::listData($this->module->getCategoryList(), 'id', 'name'), array('class' => 'span7 popover-help','empty' => Yii::t('NewsModule.news', '--выберите--'))); ?>
    </div>

    <div class="row-fluid control-group <?php echo $model->hasErrors('title') ? 'error' : ''; ?>">
        <?php echo $form->textFieldRow($model, 'title', array('size' => 60, 'maxlength' => 150, 'class' => 'span7 popover-help', 'data-original-title' => $model->getAttributeLabel('title'), 'data-content' => $model->getAttributeDescription('title'))); ?>
    </div>

    <div class="row-fluid control-group <?php echo $model->hasErrors('alias') ? 'error' : ''; ?>">
        <?php echo $form->textFieldRow($model, 'alias', array('size' => 60, 'maxlength' => 150, 'class' => 'span7 popover-help', 'data-original-title' => $model->getAttributeLabel('alias'), 'data-content' => $model->getAttributeDescription('alias'))); ?>
    </div>

    <div class="row-fluid control-group <?php echo $model->hasErrors('link') ? 'error' : ''; ?>">
        <?php echo $form->textFieldRow($model, 'link', array('size' => 60, 'maxlength' => 150, 'class' => 'span7 popover-help', 'data-original-title' => $model->getAttributeLabel('link'), 'data-content' => $model->getAttributeDescription('link'))); ?>
    </div>

    <div class="row-fluid control-group <?php echo $model->hasErrors('image') ? 'error' : ''; ?>">
        <div class="span7  popover-help"  data-original-title="<?php echo $model->getAttributeLabel('image'); ?>">
            <?php if (!$model->isNewRecord && $model->image): ?>
                <?php echo CHtml::image($model->imageUrl, $model->title, array('width'  => 300, 'height' => 300)); ?>
            <?php endif; ?>
            <?php echo $form->labelEx($model, 'image'); ?>
            <?php echo $form->fileField($model, 'image'); ?>
        </div>
        <div class="span5">
            <?php echo $form->error($model, 'image'); ?>
        </div>
    </div>
    <div class="row-fluid control-group <?php echo $model->hasErrors('full_text') ? 'error' : ''; ?>">
        <div class="span12">
            <?php echo $form->labelEx($model, 'full_text'); ?>
            <?php $this->widget($this->module->editor, array(
                'model'       => $model,
                'attribute'   => 'full_text',
                'options'     => $this->module->editorOptions,
            )); ?>
            <span class="help-block"><?php echo Yii::t('NewsModule.news', "Полный текст новости отображается при переходе по ссылке &laquo;Подробнее&raquo; или иногда при клике на заголовке новости."); ?></span>
            <?php echo $form->error($model, 'full_text'); ?>
        </div>
    </div>
    <div class="row-fluid control-group <?php echo $model->hasErrors('short_text') ? 'error' : ''; ?>">
        <div class="span12">
            <?php echo $form->labelEx($model, 'short_text'); ?>
            <?php $this->widget($this->module->editor, array(
                'model'       => $model,
                'attribute'   => 'short_text',
                'options'     => $this->module->editorOptions,
            )); ?>
            <span class="help-block"><?php echo Yii::t('NewsModule.news', "Опишите основную мысль новости или напишие некий вводный текст (анонс), пары предложений обычно достаточно. Данный текст используется при выводе списка новостей, например, на главной странице."); ?></span>
            <?php echo $form->error($model, 'short_text'); ?>
        </div>
    </div>

    <div class="row-fluid control-group <?php echo $model->hasErrors('is_protected') ? 'error' : ''; ?>">
        <?php echo $form->checkBoxRow($model, 'is_protected', $model->getProtectedStatusList()); ?>
    </div>

    <div class="row-fluid control-group <?php echo $model->hasErrors('status') ? 'error' : ''; ?>">
         <?php echo $form->dropDownListRow($model, 'status', $model->getStatusList(),array('class' => 'span7 popover-help')); ?>
    </div>

    <?php $collapse = $this->beginWidget('bootstrap.widgets.TbCollapse');?>
    <div class="accordion-group">
        <div class="accordion-heading">
            <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapseOne">
                <?php echo Yii::t('NewsModule.news','Данные для поисковой оптимизации');?>
            </a>
        </div>
        <div id="collapseOne" class="accordion-body collapse">
            <div class="accordion-inner">
                <div class="row-fluid control-group <?php echo $model->hasErrors('keywords') ? 'error' : ''; ?>">
                    <?php echo $form->textFieldRow($model, 'keywords', array('size' => 60, 'maxlength' => 150, 'class' => 'span7 popover-help', 'data-original-title' => $model->getAttributeLabel('keywords'), 'data-content' => $model->getAttributeDescription('keywords'))); ?>
                </div>
                <div class="row-fluid control-group <?php echo $model->hasErrors('description') ? 'error' : ''; ?>">
                    <?php echo $form->textAreaRow($model, 'description', array('rows' => 3, 'cols' => 98, 'class' => 'span7 popover-help', 'data-original-title' => $model->getAttributeLabel('description'), 'data-content' => $model->getAttributeDescription('description'))); ?>
                </div>
            </div>
        </div>
    </div>
    <?php $this->endWidget();?>

    <br/>

    <?php $this->widget('bootstrap.widgets.TbButton', array(
        'buttonType' => 'submit',
        'type'       => 'primary',
        'label'      => $model->isNewRecord ? Yii::t('NewsModule.news', 'Добавить новость и продолжить') : Yii::t('NewsModule.news', 'Сохранить новость и продолжить'),
    )); ?>

    <?php $this->widget('bootstrap.widgets.TbButton', array(
        'buttonType'  => 'submit',
        'htmlOptions' => array('name' => 'submit-type', 'value' => 'index'),
        'label'       => $model->isNewRecord ? Yii::t('NewsModule.news', 'Добавить новость и закрыть') : Yii::t('NewsModule.news', 'Сохранить новость и закрыть'),
    )); ?>

<?php $this->endWidget(); ?>

protected/modules/news/views/default/_search.php
<?php
$form = $this->beginWidget('bootstrap.widgets.TbActiveForm', array(
    'action'      => Yii::app()->createUrl($this->route),
    'method'      => 'get',
    'type'        => 'vertical',
    'htmlOptions' => array('class' => 'well form-vertical'),
)); ?>
    <fieldset class="inline">
        <div class="row-fluid control-group">
            <div class="span3">
                <?php echo $form->textFieldRow($model, 'id'); ?>
            </div>
            <div class="span3">
                <?php echo $form->textFieldRow($model, 'date'); ?>
            </div>
            <div class="span3">
                <?php echo $form->dropDownListRow($model, 'status', $model->statusList, array('empty' => Yii::t('NewsModule.news', '- не важен -'))); ?>
            </div>
            <div class="span3">
                <?php echo $form->dropDownListRow($model, 'category_id', CHtml::listData($this->module->categoryList, 'id', 'name'), array('empty' => Yii::t('NewsModule.news', '- не важно -'))); ?>
            </div>
        </div>
        <div class="row-fluid control-group">
            <div class="span6">
                <?php echo $form->textFieldRow($model, 'title', array('size' => 60, 'maxlength' => 150)); ?>
            </div>
            <div class="span6">
                <?php echo $form->textFieldRow($model, 'alias', array('size' => 60, 'maxlength' => 150)); ?>
            </div>
        </div>
        <div class="row-fluid control-group">
            <div class="span6">
                <?php echo $form->textFieldRow($model, 'short_text', array('size' => 60, 'maxlength' => 400)); ?>
            </div>
            <div class="span6">
                <?php echo $form->textFieldRow($model, 'full_text'); ?>
            </div>
            <div class="span10">
                <?php echo $form->checkBoxRow($model, 'is_protected', $model->protectedStatusList); ?>
            </div>
        </div>
    </fieldset>

    <?php $this->widget('bootstrap.widgets.TbButton', array(
        'type'        => 'primary',
        'encodeLabel' => false,
        'buttonType'  => 'submit',
        'label'       => '<i class="icon-search icon-white">&nbsp;</i> ' . Yii::t('blog', 'Искать новость'),
    )); ?>

<?php $this->endWidget(); ?>

protected/modules/news/views/default/create.php
<?php
    $this->breadcrumbs = array(
        Yii::app()->getModule('news')->getCategory() => array(),
        Yii::t('NewsModule.news', 'Новости') => array('/news/default/index'),
        Yii::t('NewsModule.news', 'Добавление'),
    );

    $this->pageTitle = Yii::t('NewsModule.news', 'Новости - добавление');

    $this->menu = array(
        array('icon' => 'list-alt', 'label' => Yii::t('NewsModule.news', 'Управление новостями'), 'url' => array('/news/default/index')),
        array('icon' => 'plus-sign', 'label' => Yii::t('NewsModule.news', 'Добавить новость'), 'url' => array('/news/default/create')),
    );
?>
<div class="page-header">
    <h1>
        <?php echo Yii::t('NewsModule.news', 'Новости'); ?>
        <small><?php echo Yii::t('NewsModule.news', 'добавление'); ?></small>
    </h1>
</div>

<?php echo $this->renderPartial('_form', array('model' => $model, 'languages' => $languages )); ?>

protected/modules/news/views/default/update.php
<?php
    $this->breadcrumbs = array(
        Yii::app()->getModule('news')->getCategory() => array(),
        Yii::t('NewsModule.news', 'Новости') => array('/news/default/index'),
        $model->title => array('/news/default/view', 'id' => $model->id),
        Yii::t('NewsModule.news', 'Редактирование'),
    );

    $this->pageTitle = Yii::t('NewsModule.news', 'Новости - редактирование');

    $this->menu = array(
        array('icon' => 'list-alt', 'label' => Yii::t('NewsModule.news', 'Управление новостями'), 'url' => array('/news/default/index')),
        array('icon' => 'plus-sign', 'label' => Yii::t('NewsModule.news', 'Добавить новость'), 'url' => array('/news/default/create')),
        array('label' => Yii::t('NewsModule.news', 'Новость') . ' «' . mb_substr($model->title, 0, 32) . '»'),
        array('icon' => 'pencil', 'label' => Yii::t('NewsModule.news', 'Редактирование новости'), 'url' => array(
            '/news/default/update/',
            'id' => $model->id
        )),
        array('icon' => 'eye-open', 'label' => Yii::t('NewsModule.news', 'Просмотреть новость'), 'url' => array(
            '/news/default/view',
            'id' => $model->id
        )),
        array('icon' => 'trash', 'label' => Yii::t('NewsModule.news', 'Удалить новость'), 'url' => '#', 'linkOptions' => array(
            'submit' => array('/news/default/delete', 'id' => $model->id),
            'params' => array(Yii::app()->request->csrfTokenName => Yii::app()->request->csrfToken),
            'confirm' => Yii::t('NewsModule.news', 'Вы уверены, что хотите удалить новость?'),
            'csrf' => true,
        )),
    );
?>
<div class="page-header">
    <h1>
        <?php echo Yii::t('NewsModule.news', 'Редактирование новости'); ?><br />
        <small>&laquo;<?php echo $model->title; ?>&raquo;</small>
    </h1>
</div>

<?php echo $this->renderPartial('_form', array('model' => $model, 'languages' => $languages, 'langModels' => $langModels)); ?>